**Coklu Dogrusal Regresyon Tahmini**

In [72]:
import pandas as pd
db = pd.read_csv("datasat.csv")
db = db.iloc[:,1:len(db)]
db.head()

TEL  RADIO  HABER  SATIS
0  230.1   37.8   69.2   22.1
1   44.5   39.3   45.1   10.4
2   17.2   45.9   69.3    9.3
3  151.5   41.3   58.5   18.5
4  180.8   10.8   58.4   12.9

In [73]:
X = db.drop('SATIS', axis = 1)
y = db[["SATIS"]]

In [74]:
X.head()

TEL  RADIO  HABER
0  230.1   37.8   69.2
1   44.5   39.3   45.1
2   17.2   45.9   69.3
3  151.5   41.3   58.5
4  180.8   10.8   58.4

In [75]:
y.head()

SATIS
0   22.1
1   10.4
2    9.3
3   18.5
4   12.9

In [76]:
import statsmodels.api as sm

In [77]:
lm = sm.OLS(y, X)

In [78]:
model = lm.fit()

In [79]:
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                                 OLS Regression Results                                
=======================================================================================
Dep. Variable:                  SATIS   R-squared (uncentered):                   0.982
Model:                            OLS   Adj. R-squared (uncentered):              0.982
Method:                 Least Squares   F-statistic:                              3566.
Date:                Wed, 10 May 2023   Prob (F-statistic):                   2.43e-171
Time:                        16:35:49   Log-Likelihood:                         -423.54
No. Observations:                 200   AIC:                                      853.1
Df Residuals:                     197   BIC:                                      863.0
Df Model:                           3                                                  
Covariance Type:            nonrobust                                                  
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
TEL            0.0538      0.001     40.507      0.000       0.051       0.056
RADIO          0.2222      0.009     23.595      0.000       0.204       0.241
HABER          0.0168      0.007      2.517      0.013       0.004       0.030
==============================================================================
Omnibus:                        5.982   Durbin-Watson:                   2.038
Prob(Omnibus):                  0.050   Jarque-Bera (JB):                7.039
Skew:                          -0.232   Prob(JB):                       0.0296
Kurtosis:                       3.794   Cond. No.                         12.6
==============================================================================

Notes:
[1] R² is computed without centering (uncentered) since the model does not contain a constant.
[2] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [95]:
from sklearn.linear_model import LinearRegression 
lm = LinearRegression()

In [96]:
model = lm.fit(X, y)

In [97]:
model.intercept_

array([2.93888937])

In [98]:
model.coef_

array([[ 0.04576465,  0.18853002, -0.00103749]])

**TAHMIN**

**SATIS = 2.94 + TEL * 0.04 + RADIO 0.19 - HABER * 0.001**
**Tahmin Islemini Gercektestirecerk fonksiyon**

**30 Birim TEL, 10 Birim RADIO, 40 Birim HABER **

In [99]:
2.94 + 30 * 0.04 + 10 * 0.19 - 40 * 0.001

5.999999999999999

In [113]:
new_data = [300], [120], [400]

In [114]:
import pandas as pd
new_data =pd.DataFrame(new_data).T

In [115]:
new_data

0    1    2
0  300  120  400

In [116]:
model.predict(new_data)

C:\Users\qasem\anaconda3\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[38.87688782]])

**Hata Kare Ortalamasi**

In [118]:
from sklearn.metrics import mean_squared_error

In [119]:
model.predict(X)[0:10]

array([[20.52397441],
       [12.33785482],
       [12.30767078],
       [17.59782951],
       [13.18867186],
       [12.47834763],
       [11.72975995],
       [12.12295317],
       [ 3.72734086],
       [12.55084872]])

In [122]:
MSE = mean_squared_error(y, model.predict(X))
MSE

2.784126314510936

In [123]:
import numpy as np
RMSE = np.sqrt(MSE)
RMSE

1.6685701407225697